# Generated by Django 3.2.12 on 2022-03-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220326_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationsettings',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='to enable notification'),
        ),
    ]
