# Generated by Django 4.1.2 on 2022-10-05 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usernotificationsettings_is_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotificationsettings',
            name='type',
        ),
    ]
