# Generated by Django 4.2 on 2023-04-11 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_usernotificationsettings_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserNotificationSettings",
        ),
    ]
